# -*- coding: utf-8 -*-
"""LAB1_3374_LIM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4i1qN3wu_lVGaOaNyNaGHs6J8HxzjT-
"""

# Лабораторная работа 1
# 3374
# Лобачев Иван Максимович
# Исследование набора данных

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline
plt.rcParams['figure.figsize'] = (12, 8)
sns.set_style("whitegrid")

# Загрузка датасета
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=';')
print(f"Размер датасета: {df.shape}")
print(f"Колонки: {list(df.columns)}")

# Описание датасета
print("Red Wine Quality (UCI) - Классификация качества вина по хим. параметрам")
print(f"Признаки: {len(df.columns)-1} числовых, Целевая: quality ({df['quality'].min()}-{df['quality'].max()})")

# Просмотр первых строк
print("Первые строки данных:")
display(df.head())
# Базовая информация о данных
print("Информация о данных:")
df.info()
print("Базовая статистика:")
display(df.describe())

# Анализ пропущенных значений
missing_data = df.isnull().sum()
print("Пропущенные значения:")
print(missing_data)
print(f"Всего: {missing_data.sum()}")
if missing_data.sum() == 0:
    print("Пропусков нет")
else:
    for col, count in missing_data[missing_data > 0].items():
        print(f"{col}: {count} ({(count/len(df))*100:.1f}%)")

# Статистики атрибутов
stats_df = pd.DataFrame({
    'Среднее': df.mean(),
    'Стандартное отклонение': df.std(),
    'Медиана': df.median(),
    'Минимум': df.min(),
    'Максимум': df.max()
})
display(stats_df.round(3))

# Гистограммы распределения
fig, axes = plt.subplots(4, 3, figsize=(15, 12))
axes = axes.ravel()
for i, column in enumerate(df.columns):
    df[column].hist(bins=30, ax=axes[i], alpha=0.7)
    axes[i].set_title(column, fontsize=10)
    axes[i].axvline(df[column].mean(), color='red', linestyle='--', linewidth=1)
    axes[i].axvline(df[column].median(), color='green', linestyle='--', linewidth=1)
plt.tight_layout()
plt.show()
print("Анализ: нормальные распределения, правосторонняя асимметрия в residual sugar, free sulfur dioxide")

# Анализ выбросов
fig, axes = plt.subplots(4, 3, figsize=(15, 12))
axes = axes.ravel()
for i, column in enumerate(df.columns):
    df.boxplot(column=column, ax=axes[i])
    axes[i].set_title(column, fontsize=10)

plt.tight_layout()
plt.show()
# Количественный анализ выбросов
def count_outliers(column):
    Q1, Q3 = column.quantile(0.25), column.quantile(0.75)
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    return len(column[(column < lower) | (column > upper)])
outliers_data = [(col, count_outliers(df[col]), f"{(count_outliers(df[col])/len(df))*100:.1f}%")
                for col in df.columns]
outliers_df = pd.DataFrame(outliers_data, columns=['Признак', 'Выбросы', '%'])
display(outliers_df)
# Вывод
high_outliers = outliers_df[outliers_df['%'].str.replace('%','').astype(float) > 5]
if not high_outliers.empty:
    print("Много выбросов (>5%):", ", ".join(high_outliers['Признак'].tolist()))

print("Матрица корреляций:")
# Вычисляем матрицу корреляций
correlation_matrix = df.corr()
# Визуализируем тепловую карту
plt.figure(figsize=(12, 10))
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))
sns.heatmap(correlation_matrix, mask=mask, annot=True, cmap='coolwarm', center=0,
            square=True, linewidths=0.5, fmt='.2f', cbar_kws={"shrink": .8})
plt.title('Матрица корреляций между признаками', fontsize=14, pad=20)
plt.tight_layout()
plt.show()

# Анализ корреляций
corr_matrix = df.corr()
# Сильные корреляции (>0.5)
print("Сильные корреляции (|r|>0.5):")
strong_corr = []
for i in range(len(corr_matrix.columns)):
    for j in range(i+1, len(corr_matrix.columns)):
        corr_val = corr_matrix.iloc[i, j]
        if abs(corr_val) > 0.5:
            strong_corr.append((corr_matrix.columns[i], corr_matrix.columns[j], corr_val))

for col1, col2, corr in sorted(strong_corr, key=lambda x: abs(x[2]), reverse=True):
    print(f"{col1} <-> {col2}: {corr:.3f}")
# Корреляции с качеством
print("Корреляции с quality:")
quality_corr = corr_matrix['quality'].sort_values(ascending=False)
for feat, corr in quality_corr.items():
    if feat != 'quality' and abs(corr) > 0.1:
        print(f"{feat}: {corr:.3f}")

# Матрица графиков рассеивания для ключевых признаков
print("МАТРИЦА ГРАФИКОВ РАССЕИВАНИЯ ДЛЯ КЛЮЧЕВЫХ ПРИЗНАКОВ:")

# Вычисляем матрицу корреляций
corr_matrix = df.corr()

# Выбираем 4 наиболее коррелированных с качеством признака
top_features = corr_matrix['quality'].abs().sort_values(ascending=False).index[1:5]
print(f"Анализируемые признаки: {list(top_features)}")

# Строим pairplot
analysis_features = list(top_features) + ['quality']
g = sns.pairplot(df[analysis_features], diag_kind='hist', hue='quality',
                 palette='RdYlBu', plot_kws={'alpha':0.7, 's':50})
plt.suptitle('Взаимосвязи ключевых признаков с качеством вина', y=1.02, fontsize=14)
plt.show()

print("АНАЛИЗ ВЗАИМОСВЯЗЕЙ:")
print("Alcohol <-> Quality: четкая положительная тенденция - чем выше алкоголь, тем лучше качество")
print("Volatile acidity <-> Quality: явная отрицательная зависимость - высокая летучая кислотность ухудшает качество")
print("Sulphates <-> Quality: слабая положительная корреляция")
print("Citric acid <-> Quality: умеренная положительная связь")
print("НАБЛЮДЕНИЯ:")
print("Качество вина образует кластеры по уровням (5,6,7)")
print("Высококачественные вина (7-8) концентрируются в области высокого alcohol и низкой volatile acidity")
print("Некоторые пары признаков показывают нелинейные зависимости")

"""
ВЫВОД:

1. ДАТАСЕТ:
   Набор данных: Red Wine Quality (UCI)
   Предметная область: химические параметры красного вина
   Характер данных: реальные измерения

2. СТАТИСТИЧЕСКИЙ АНАЛИЗ:
   Пропущенные значения отсутствуют
   Выявлены выбросы в признаках: residual sugar, free sulfur dioxide
   Распределения близки к нормальным с правосторонней асимметрией

3. КОРРЕЛЯЦИОННЫЙ АНАЛИЗ:
   Сильные корреляции: density-fixed acidity, free-total sulfur dioxide
   Качество вина наиболее зависит от: alcohol (положительно), volatile acidity (отрицательно)
   Слабые корреляции: pH-citric acid, residual sugar-other features

4. ВЗАИМОСВЯЗИ ПРИЗНАКОВ:
   Alcohol положительно влияет на качество
   Volatile acidity отрицательно влияет на качество
   Sulphates и citric acid слабо положительно коррелируют с качеством

5. КЛАСТЕРИЗАЦИЯ ПО КАЧЕСТВУ:
   Вина естественно группируются по уровням качества (5,6,7)
   Высококачественные вина концентрируются в области высокого alcohol и низкой volatile acidity
"""